In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [68]:
df = load_wine()
data = pd.DataFrame(df['data'])

data1 = data.loc[:,9:12]
data2 = data1.drop(columns = 10)

X = data2
y = df.target

x_train, x_test, y_train, y_test =  train_test_split(X, y, test_size=0.25, random_state=17)

dtc = DecisionTreeClassifier()

dtc_model = dtc.fit(x_train,y_train)

dtc_predictions = dtc.predict(x_test)
dtc_predictions

array([1, 1, 1, 0, 2, 2, 0, 1, 2, 0, 2, 0, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 0, 1, 2, 1, 2, 1, 0, 0, 2, 1, 0, 1, 1, 1, 2, 1, 1, 2,
       2])

In [73]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

skf = StratifiedKFold(n_splits=5, random_state=17, shuffle=True)



In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [71]:
lreg = LogisticRegression(random_state =17,multi_class='ovr')

lreg_model = lreg.fit(x_train,y_train)

lreg_predictions = lreg.predict(x_test)
lreg_predictions

array([1, 1, 1, 0, 2, 1, 0, 1, 2, 0, 2, 0, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1,
       0, 2, 1, 1, 0, 1, 2, 1, 2, 1, 0, 0, 2, 1, 0, 1, 1, 1, 2, 1, 1, 2,
       2])

In [77]:
print(cross_val_score(lreg, X, y, cv=skf).mean())

0.9330158730158731


In [78]:
print(cross_val_score(lreg, X, y).mean())

0.9442857142857143


In [88]:
accuracy_score(y_test,lreg_predictions)

0.9111111111111111

In [79]:
from sklearn.svm import SVC

In [81]:
svc = SVC(random_state =17,decision_function_shape='ovr')

svc_model = svc.fit(x_train,y_train)

svc_predictions = svc.predict(x_test)
svc_predictions

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1])

In [82]:
print(cross_val_score(svc, X, y, cv=skf).mean())

0.6803174603174603


In [83]:
print(cross_val_score(svc, X, y).mean())

0.6804761904761905


In [89]:
accuracy_score(y_test,svc_predictions)

0.6222222222222222

In [91]:
from sklearn.metrics import classification_report, confusion_matrix

confusion_matrix(y_test, lreg_predictions) #путает 1 и 2

array([[ 9,  0,  0],
       [ 0, 19,  0],
       [ 0,  4, 13]], dtype=int64)

In [92]:
confusion_matrix(y_test, svc_predictions) # путает 1 и 2

array([[ 9,  0,  0],
       [ 0, 19,  0],
       [ 2, 15,  0]], dtype=int64)

In [93]:
classification_report(y_test, lreg_predictions)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00         9\n           1       0.83      1.00      0.90        19\n           2       1.00      0.76      0.87        17\n\n    accuracy                           0.91        45\n   macro avg       0.94      0.92      0.92        45\nweighted avg       0.93      0.91      0.91        45\n'

In [94]:
classification_report(y_test, svc_predictions)

C:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


'              precision    recall  f1-score   support\n\n           0       0.82      1.00      0.90         9\n           1       0.56      1.00      0.72        19\n           2       0.00      0.00      0.00        17\n\n    accuracy                           0.62        45\n   macro avg       0.46      0.67      0.54        45\nweighted avg       0.40      0.62      0.48        45\n'